[tool.ruff]
line-length = 120
target-version = "py311"
fix = true

[tool.ruff.lint]
select = ["E", "F", "N"]  # Errors, Pyflakes, Naming
ignore = ["E203", "F401", "E501"]  # whitespace-before-punctuation, unused-import, line-too-long

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.isort]
line_length = 120
include_trailing_comma = false
use_parentheses = true
ensure_newline_before_comments = false
combine_as_imports = true
